# Generated by Django 3.0.4 on 2020-03-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='lastName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
