# Generated by Django 3.0.4 on 2020-03-27 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0003_auto_20200327_1411'),
        ('student', '0003_auto_20200327_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('class_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=30)),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='QuizInfo',
            fields=[
                ('quiz_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('quiz_name', models.CharField(max_length=50)),
                ('launch_time', models.DateTimeField(verbose_name='Date to Launch Quiz')),
                ('class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.ClassInfo')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('question_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('MCQ', 'MCQ'), ('Blanks', 'Fill blanks')], default='MCQ', max_length=15)),
                ('question', models.CharField(max_length=200)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizInfo')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_choice', models.CharField(max_length=100)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_answer', models.CharField(max_length=100)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='ClassEnrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.ClassInfo')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
            options={
                'unique_together': {('class_code', 'student_id')},
            },
        ),
    ]
