# Generated by Django 3.0.4 on 2020-03-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lastName',
            field=models.CharField(max_length=50),
        ),
    ]
